defmodule Buckets.Repo.Migrations.AddEntryAndSchedule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bucket_entry, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :bucket_id,
          references(:bucket,
            column: :id,
            name: "bucket_entry_bucket_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :from, :utc_datetime, null: false
      add :to, :utc_datetime
    end

    alter table(:bucket) do
      add :schedule, :map, null: false
    end
  end

  def down do
    alter table(:bucket) do
      remove :schedule
    end

    drop constraint(:bucket_entry, "bucket_entry_bucket_id_fkey")

    drop table(:bucket_entry)
  end
end
