defmodule Buckets.Repo.Migrations.AddBucketUserRelation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bucket_entry) do
      modify :to, :utc_datetime, null: true
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:bucket) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")

      add :user_id,
          references(:users,
            column: :id,
            name: "bucket_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bucket, "bucket_user_id_fkey")

    alter table(:bucket) do
      remove :user_id
      modify :id, :uuid, default: nil
    end

    alter table(:bucket_entry) do
      modify :id, :uuid, default: nil
      modify :to, :utc_datetime, null: false
    end
  end
end
