import * as Types from './types/generated';

import { api } from './api';

            /* eslint-disable */
            /**
             *
             * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
             *
             * instead, edit one of the `.gql` files in this project and run
             *
             * npm run codegen
             *
             * for this file to be re-created
             */ 
          
export type BucketsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type BucketsQuery = { __typename?: 'RootQueryType', buckets: Array<{ __typename?: 'Bucket', id: string, name: string }> };


export const BucketsDocument = `
    query Buckets {
  buckets {
    id
    name
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    Buckets: build.query<BucketsQuery, BucketsQueryVariables | void>({
      query: (variables) => ({ document: BucketsDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useBucketsQuery, useLazyBucketsQuery } = injectedRtkApi;

