version: "3.7"

services:

  # Install a separate instance for development
  postgres-dev:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  # Install a separate instance for integration tests
  #
  # The instance is trimmed for performance
  # - disables certain checks
  # - stores data in memory (rather than file system)
  #
  # inspired by: https://github.com/testjavascript/nodejs-integration-tests-best-practices#postgres
  postgres-test:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # Trim for performance:
    # fsync=off means don't wait for disc acknowledgement
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0 -c log_statement=all
    # store data in memory
    tmpfs:
      - /var/lib/postgresql/data
