defmodule Buckets.Repo.Migrations.AddTrackingResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bucket_entry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bucket_id, :uuid, null: false
      add :from, :utc_datetime, null: false
      add :to, :utc_datetime
    end

    create table(:bucket, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bucket_entry) do
      modify :bucket_id,
             references(:bucket,
               column: :id,
               name: "bucket_entry_bucket_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bucket) do
      add :name, :text, null: false
      add :schedule, :map, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "bucket_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:bucket, "bucket_user_id_fkey")

    alter table(:bucket) do
      remove :user_id
      remove :schedule
      remove :name
    end

    drop constraint(:bucket_entry, "bucket_entry_bucket_id_fkey")

    alter table(:bucket_entry) do
      modify :bucket_id, :uuid
    end

    drop table(:bucket)

    drop table(:bucket_entry)
  end
end
