import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "http://localhost:4000/gql",
  documents: "./src/**/*.gql",
  generates: {
    "src/types/generated.ts": {
      plugins: ["typescript"],
      config: {
        maybeValue: "T",
      },
    },
    "src/": {
      preset: "near-operation-file",
      presetConfig: {
        baseTypesPath: "types/generated.ts",
      },
      plugins: [
        "typescript-operations",
        {
          add: {
            content: `
            /* eslint-disable */
            /**
             *
             * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
             *
             * instead, edit one of the \`.gql\` files in this project and run
             *
             * npm run codegen
             *
             * for this file to be re-created
             */ 
          `,
          },
        },
        // {
        //   add: {
        //     content: "module.hot?.accept();",
        //   },
        // },
        {
          "typescript-rtk-query": {
            importBaseApiFrom: "./api",
            exportHooks: true,
            // overrideExisting: 'module.hot?.status() === "apply"',
          },
        },
      ],
    },
  },
};

export default config;
